theme: jekyll-theme-minimal
title: Welcome to my geek world. 
description: This site will be about my journey in the big data world, Im not trying to be the best but if I can daydreaming of it, I will make it happen someday.
